spring:
  datasource:
    url: jdbc:h2:mem:chatapp
    username: sa
    password:

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl

  h2:
    console:
      enabled: true

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .ftl

jwt:
  public-key: certs/apiKey.jks
  alias: apiKey
  password: pass1234